// netlify-build.js - Creates firebase-config.js from Netlify env vars
const fs = require('fs');
const path = require('path');

const configContent = `// Auto-generated by Netlify build
import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import { getAuth } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import { getFirestore, enableIndexedDbPersistence } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

const firebaseConfig = {
    apiKey: "${process.env.API_KEY}",
    authDomain: "${process.env.AUTH_DOMAIN}",
    projectId: "${process.env.PROJECT_ID}",
    storageBucket: "${process.env.STORAGE_BUCKET}",
    messagingSenderId: "${process.env.MESSAGING_SENDER_ID}",
    appId: "${process.env.APP_ID}"
};

const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);

enableIndexedDbPersistence(db).catch((err) => {
    if (err.code === 'failed-precondition') {
        console.warn('Offline persistence failed: Multiple tabs open');
    } else if (err.code === 'unimplemented') {
        console.warn('Browser doesn\\'t support offline persistence');
    }
});

export { auth, db };
`;

const targetPath = path.join(__dirname, 'js', 'firebase-config.js');
fs.writeFileSync(targetPath, configContent);
console.log('✅ firebase-config.js generated from environment variables.');